
Vagrant.configure("2") do |config|

  config.vm.box = "chef/centos-6.5"

  config.vm.network :forwarded_port, guest: 4440, host: 14440

  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.provision :shell, :path => "add-project.sh", :args => "examples"

end
